### ISSUE TITLE
WireFrame - Travis

### ISSUE THREAD

**Issue by travisnash99** [monicaj314/rollinit#1]

**Comment by monicaj314** [comment]
Something i scribbled up ![screen shot 2017-06-13 at 6 38 55 pm](https://user-images.githubusercontent.com/16677935/27109327-c3710c6e-5067-11e7-8411-a6e9fd4766ef.png)

**Comment by monicaj314** [comment]
![image uploaded from ios 1](https://user-images.githubusercontent.com/16677935/27257415-4d5b9436-539b-11e7-877e-6f4c64b71f43.jpg)
